// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1089: (x0,x1) => x0.getContext(x1),
      _1091: x0 => x0.convertToBlob(),
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1286: (x0,x1) => x0.createElement(x1),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1293: () => globalThis.window.navigator.userAgent,
      _1295: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1296: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1297: (x0,x1) => x0.createElement(x1),
      _1304: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1331: () => globalThis.firebase_firestore.documentId(),
      _1332: (x0,x1) => new firebase_firestore.GeoPoint(x0,x1),
      _1333: x0 => globalThis.firebase_firestore.vector(x0),
      _1334: x0 => globalThis.firebase_firestore.Bytes.fromUint8Array(x0),
      _1336: (x0,x1) => globalThis.firebase_firestore.collection(x0,x1),
      _1338: (x0,x1) => globalThis.firebase_firestore.doc(x0,x1),
      _1341: x0 => x0.call(),
      _1379: (x0,x1) => globalThis.firebase_firestore.setDoc(x0,x1),
      _1392: x0 => globalThis.firebase_firestore.doc(x0),
      _1407: () => globalThis.firebase_firestore.serverTimestamp(),
      _1417: (x0,x1) => globalThis.firebase_firestore.getFirestore(x0,x1),
      _1419: x0 => globalThis.firebase_firestore.Timestamp.fromMillis(x0),
      _1420: (module,f) => finalizeWrapper(f, function() { return module.exports._1420(f,arguments.length) }),
      _1568: x0 => x0.path,
      _1591: x0 => x0.path,
      _1695: x0 => x0.decode(),
      _1696: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1697: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1698: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1698(f,arguments.length,x0) }),
      _1699: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1699(f,arguments.length,x0) }),
      _1700: x0 => x0.send(),
      _1701: () => new XMLHttpRequest(),
      _1722: x0 => x0.toJSON(),
      _1723: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1723(f,arguments.length,x0) }),
      _1724: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1724(f,arguments.length,x0) }),
      _1725: (x0,x1,x2) => x0.onAuthStateChanged(x1,x2),
      _1726: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1726(f,arguments.length,x0) }),
      _1727: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1727(f,arguments.length,x0) }),
      _1728: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1728(f,arguments.length,x0) }),
      _1729: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1729(f,arguments.length,x0) }),
      _1730: (x0,x1,x2) => x0.onIdTokenChanged(x1,x2),
      _1742: x0 => globalThis.firebase_auth.signInAnonymously(x0),
      _1750: (x0,x1) => globalThis.firebase_auth.connectAuthEmulator(x0,x1),
      _1773: x0 => globalThis.firebase_auth.OAuthProvider.credentialFromResult(x0),
      _1788: x0 => globalThis.firebase_auth.getAdditionalUserInfo(x0),
      _1789: (x0,x1,x2) => ({errorMap: x0,persistence: x1,popupRedirectResolver: x2}),
      _1790: (x0,x1) => globalThis.firebase_auth.initializeAuth(x0,x1),
      _1796: x0 => globalThis.firebase_auth.OAuthProvider.credentialFromError(x0),
      _1811: () => globalThis.firebase_auth.debugErrorMap,
      _1814: () => globalThis.firebase_auth.browserSessionPersistence,
      _1816: () => globalThis.firebase_auth.browserLocalPersistence,
      _1818: () => globalThis.firebase_auth.indexedDBLocalPersistence,
      _1821: x0 => globalThis.firebase_auth.multiFactor(x0),
      _1822: (x0,x1) => globalThis.firebase_auth.getMultiFactorResolver(x0,x1),
      _1824: x0 => x0.currentUser,
      _1838: x0 => x0.displayName,
      _1839: x0 => x0.email,
      _1840: x0 => x0.phoneNumber,
      _1841: x0 => x0.photoURL,
      _1842: x0 => x0.providerId,
      _1843: x0 => x0.uid,
      _1844: x0 => x0.emailVerified,
      _1845: x0 => x0.isAnonymous,
      _1846: x0 => x0.providerData,
      _1847: x0 => x0.refreshToken,
      _1848: x0 => x0.tenantId,
      _1849: x0 => x0.metadata,
      _1851: x0 => x0.providerId,
      _1852: x0 => x0.signInMethod,
      _1853: x0 => x0.accessToken,
      _1854: x0 => x0.idToken,
      _1855: x0 => x0.secret,
      _1867: x0 => x0.creationTime,
      _1868: x0 => x0.lastSignInTime,
      _1873: x0 => x0.code,
      _1875: x0 => x0.message,
      _1887: x0 => x0.email,
      _1888: x0 => x0.phoneNumber,
      _1889: x0 => x0.tenantId,
      _1912: x0 => x0.user,
      _1915: x0 => x0.providerId,
      _1916: x0 => x0.profile,
      _1917: x0 => x0.username,
      _1918: x0 => x0.isNewUser,
      _1921: () => globalThis.firebase_auth.browserPopupRedirectResolver,
      _1926: x0 => x0.displayName,
      _1927: x0 => x0.enrollmentTime,
      _1928: x0 => x0.factorId,
      _1929: x0 => x0.uid,
      _1931: x0 => x0.hints,
      _1932: x0 => x0.session,
      _1934: x0 => x0.phoneNumber,
      _1946: (x0,x1) => x0.getItem(x1),
      _1952: (x0,x1) => x0.appendChild(x1),
      _1955: (x0,x1,x2,x3) => globalThis.firebase_analytics.logEvent(x0,x1,x2,x3),
      _1957: (x0,x1) => globalThis.firebase_analytics.setAnalyticsCollectionEnabled(x0,x1),
      _1960: (x0,x1) => globalThis.firebase_analytics.initializeAnalytics(x0,x1),
      _1963: (x0,x1,x2) => x0.setItem(x1,x2),
      _1964: (x0,x1) => x0.querySelector(x1),
      _1965: x0 => ({type: x0}),
      _1966: (x0,x1) => new Blob(x0,x1),
      _1967: x0 => globalThis.URL.createObjectURL(x0),
      _1968: (x0,x1) => x0.item(x1),
      _1969: () => new FileReader(),
      _1970: (x0,x1) => x0.readAsDataURL(x1),
      _1972: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1972(f,arguments.length,x0) }),
      _1973: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1974: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1974(f,arguments.length,x0) }),
      _1975: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1976: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1976(f,arguments.length,x0) }),
      _1977: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1977(f,arguments.length,x0) }),
      _1978: (x0,x1) => x0.removeChild(x1),
      _1979: x0 => x0.click(),
      _1980: x0 => new Blob(x0),
      _1981: x0 => globalThis.URL.revokeObjectURL(x0),
      _1984: (x0,x1,x2,x3,x4,x5,x6,x7) => ({apiKey: x0,authDomain: x1,databaseURL: x2,projectId: x3,storageBucket: x4,messagingSenderId: x5,measurementId: x6,appId: x7}),
      _1985: (x0,x1) => globalThis.firebase_core.initializeApp(x0,x1),
      _1986: x0 => globalThis.firebase_core.getApp(x0),
      _1987: () => globalThis.firebase_core.getApp(),
      _1988: (x0,x1,x2) => globalThis.firebase_core.registerVersion(x0,x1,x2),
      _1990: () => globalThis.firebase_core.SDK_VERSION,
      _1996: x0 => x0.apiKey,
      _1998: x0 => x0.authDomain,
      _2000: x0 => x0.databaseURL,
      _2002: x0 => x0.projectId,
      _2004: x0 => x0.storageBucket,
      _2006: x0 => x0.messagingSenderId,
      _2008: x0 => x0.measurementId,
      _2010: x0 => x0.appId,
      _2012: x0 => x0.name,
      _2013: x0 => x0.options,
      _2016: (x0,x1) => x0.debug(x1),
      _2017: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2017(f,arguments.length,x0) }),
      _2018: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._2018(f,arguments.length,x0,x1) }),
      _2019: (x0,x1) => ({createScript: x0,createScriptURL: x1}),
      _2020: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _2021: (x0,x1) => x0.createScriptURL(x1),
      _2022: (x0,x1,x2) => x0.createScript(x1,x2),
      _2023: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2023(f,arguments.length,x0) }),
      _2024: (x0,x1) => x0.key(x1),
      _2034: Date.now,
      _2036: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _2037: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _2038: () => new Error().stack,
      _2039: () => typeof dartUseDateNowForTicks !== "undefined",
      _2040: () => 1000 * performance.now(),
      _2041: () => Date.now(),
      _2042: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _2043: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _2044: () => new WeakMap(),
      _2045: (map, o) => map.get(o),
      _2046: (map, o, v) => map.set(o, v),
      _2047: (exn) => exn.toString(),
      _2048: (exn) => exn.stack,
      _2049: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _2050: x0 => new WeakRef(x0),
      _2051: x0 => x0.deref(),
      _2058: () => globalThis.WeakRef,
      _2061: s => JSON.stringify(s),
      _2062: s => printToConsole(s),
      _2063: (o, p, r) => o.replaceAll(p, () => r),
      _2064: (o, p, r) => o.replace(p, () => r),
      _2065: Function.prototype.call.bind(String.prototype.toLowerCase),
      _2066: s => s.toUpperCase(),
      _2067: s => s.trim(),
      _2068: s => s.trimLeft(),
      _2069: s => s.trimRight(),
      _2070: (string, times) => string.repeat(times),
      _2071: Function.prototype.call.bind(String.prototype.indexOf),
      _2072: (s, p, i) => s.lastIndexOf(p, i),
      _2073: (string, token) => string.split(token),
      _2074: Object.is,
      _2077: (o, t) => typeof o === t,
      _2078: (o, c) => o instanceof c,
      _2079: o => Object.keys(o),
      _2082: (o, a) => o + a,
      _2109: x0 => new Array(x0),
      _2111: x0 => x0.length,
      _2113: (x0,x1) => x0[x1],
      _2114: (x0,x1,x2) => { x0[x1] = x2 },
      _2117: (x0,x1,x2) => new DataView(x0,x1,x2),
      _2119: x0 => new Int8Array(x0),
      _2120: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _2122: x0 => new Uint8ClampedArray(x0),
      _2124: x0 => new Int16Array(x0),
      _2126: x0 => new Uint16Array(x0),
      _2128: x0 => new Int32Array(x0),
      _2130: x0 => new Uint32Array(x0),
      _2132: x0 => new Float32Array(x0),
      _2134: x0 => new Float64Array(x0),
      _2158: x0 => x0.random(),
      _2161: () => globalThis.Math,
      _2174: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _2175: (handle) => clearTimeout(handle),
      _2176: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _2177: (handle) => clearInterval(handle),
      _2178: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _2179: () => Date.now(),
      _2180: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _2181: (x0,x1) => x0.exec(x1),
      _2182: (x0,x1) => x0.test(x1),
      _2183: x0 => x0.pop(),
      _2185: o => o === undefined,
      _2187: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _2189: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _2190: o => o instanceof RegExp,
      _2191: (l, r) => l === r,
      _2192: o => o,
      _2193: o => o,
      _2194: o => o,
      _2195: b => !!b,
      _2196: o => o.length,
      _2198: (o, i) => o[i],
      _2199: f => f.dartFunction,
      _2200: () => ({}),
      _2201: () => [],
      _2203: () => globalThis,
      _2204: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _2205: (o, p) => p in o,
      _2206: (o, p) => o[p],
      _2207: (o, p, v) => o[p] = v,
      _2208: (o, m, a) => o[m].apply(o, a),
      _2210: o => String(o),
      _2211: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _2212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2212(f,arguments.length,x0) }),
      _2213: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._2213(f,arguments.length,x0,x1) }),
      _2214: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _2215: o => [o],
      _2216: (o0, o1) => [o0, o1],
      _2217: (o0, o1, o2) => [o0, o1, o2],
      _2218: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _2219: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2220: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2221: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2222: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2223: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2224: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2225: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2226: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2227: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2228: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2229: x0 => new ArrayBuffer(x0),
      _2230: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _2231: x0 => x0.input,
      _2232: x0 => x0.index,
      _2233: x0 => x0.groups,
      _2234: x0 => x0.flags,
      _2235: x0 => x0.multiline,
      _2236: x0 => x0.ignoreCase,
      _2237: x0 => x0.unicode,
      _2238: x0 => x0.dotAll,
      _2239: (x0,x1) => { x0.lastIndex = x1 },
      _2240: (o, p) => p in o,
      _2241: (o, p) => o[p],
      _2242: (o, p, v) => o[p] = v,
      _2243: (o, p) => delete o[p],
      _2251: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2251(f,arguments.length,x0) }),
      _2252: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2252(f,arguments.length,x0) }),
      _2257: (x0,x1) => new WebSocket(x0,x1),
      _2258: (x0,x1) => x0.send(x1),
      _2259: (x0,x1,x2) => x0.close(x1,x2),
      _2261: x0 => x0.close(),
      _2264: () => new AbortController(),
      _2265: x0 => x0.abort(),
      _2266: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _2267: (x0,x1) => globalThis.fetch(x0,x1),
      _2268: (x0,x1) => x0.get(x1),
      _2269: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._2269(f,arguments.length,x0,x1,x2) }),
      _2270: (x0,x1) => x0.forEach(x1),
      _2271: x0 => x0.getReader(),
      _2272: x0 => x0.cancel(),
      _2273: x0 => x0.read(),
      _2274: x0 => x0.trustedTypes,
      _2275: (x0,x1) => { x0.text = x1 },
      _2276: o => o instanceof Array,
      _2277: (a, i) => a.push(i),
      _2280: (a, l) => a.length = l,
      _2281: a => a.pop(),
      _2282: (a, i) => a.splice(i, 1),
      _2284: (a, s, e) => a.slice(s, e),
      _2286: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _2287: a => a.length,
      _2289: (a, i) => a[i],
      _2290: (a, i, v) => a[i] = v,
      _2292: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _2293: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _2295: o => o instanceof Uint8Array,
      _2296: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _2297: o => o instanceof Int8Array,
      _2298: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _2299: o => o instanceof Uint8ClampedArray,
      _2300: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _2301: o => o instanceof Uint16Array,
      _2302: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _2303: o => o instanceof Int16Array,
      _2304: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _2305: o => o instanceof Uint32Array,
      _2306: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _2307: o => o instanceof Int32Array,
      _2308: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _2310: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _2311: o => o instanceof Float32Array,
      _2312: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _2313: o => o instanceof Float64Array,
      _2314: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _2315: (t, s) => t.set(s),
      _2317: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _2319: o => o.buffer,
      _2320: o => o.byteOffset,
      _2321: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _2322: (b, o) => new DataView(b, o),
      _2323: (b, o, l) => new DataView(b, o, l),
      _2324: Function.prototype.call.bind(DataView.prototype.getUint8),
      _2325: Function.prototype.call.bind(DataView.prototype.setUint8),
      _2326: Function.prototype.call.bind(DataView.prototype.getInt8),
      _2327: Function.prototype.call.bind(DataView.prototype.setInt8),
      _2328: Function.prototype.call.bind(DataView.prototype.getUint16),
      _2329: Function.prototype.call.bind(DataView.prototype.setUint16),
      _2330: Function.prototype.call.bind(DataView.prototype.getInt16),
      _2331: Function.prototype.call.bind(DataView.prototype.setInt16),
      _2332: Function.prototype.call.bind(DataView.prototype.getUint32),
      _2333: Function.prototype.call.bind(DataView.prototype.setUint32),
      _2334: Function.prototype.call.bind(DataView.prototype.getInt32),
      _2335: Function.prototype.call.bind(DataView.prototype.setInt32),
      _2338: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _2339: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _2340: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _2341: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _2342: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _2343: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _2344: Function.prototype.call.bind(Number.prototype.toString),
      _2345: Function.prototype.call.bind(BigInt.prototype.toString),
      _2346: Function.prototype.call.bind(Number.prototype.toString),
      _2347: (d, digits) => d.toFixed(digits),
      _2360: () => globalThis.document,
      _2366: (x0,x1) => { x0.height = x1 },
      _2368: (x0,x1) => { x0.width = x1 },
      _2370: (x0,x1) => { x0.pointerEvents = x1 },
      _2379: x0 => x0.style,
      _2382: x0 => x0.src,
      _2383: (x0,x1) => { x0.src = x1 },
      _2384: x0 => x0.naturalWidth,
      _2385: x0 => x0.naturalHeight,
      _2401: x0 => x0.status,
      _2402: (x0,x1) => { x0.responseType = x1 },
      _2404: x0 => x0.response,
      _2514: (x0,x1) => { x0.draggable = x1 },
      _2530: x0 => x0.style,
      _2887: (x0,x1) => { x0.target = x1 },
      _2889: (x0,x1) => { x0.download = x1 },
      _2914: (x0,x1) => { x0.href = x1 },
      _3459: (x0,x1) => { x0.accept = x1 },
      _3473: x0 => x0.files,
      _3499: (x0,x1) => { x0.multiple = x1 },
      _3517: (x0,x1) => { x0.type = x1 },
      _3769: (x0,x1) => { x0.type = x1 },
      _3777: (x0,x1) => { x0.crossOrigin = x1 },
      _3779: (x0,x1) => { x0.text = x1 },
      _4236: () => globalThis.window,
      _4276: x0 => x0.document,
      _4279: x0 => x0.location,
      _4298: x0 => x0.navigator,
      _4560: x0 => x0.trustedTypes,
      _4561: x0 => x0.sessionStorage,
      _4562: x0 => x0.localStorage,
      _4577: x0 => x0.hostname,
      _4687: x0 => x0.userAgent,
      _4738: x0 => x0.data,
      _4895: x0 => x0.length,
      _5112: x0 => x0.readyState,
      _5121: x0 => x0.protocol,
      _5125: (x0,x1) => { x0.binaryType = x1 },
      _5128: x0 => x0.code,
      _5129: x0 => x0.reason,
      _6837: x0 => x0.signal,
      _6892: x0 => x0.baseURI,
      _6898: x0 => x0.firstChild,
      _6909: () => globalThis.document,
      _6992: x0 => x0.head,
      _7323: (x0,x1) => { x0.id = x1 },
      _7350: x0 => x0.children,
      _8669: x0 => x0.value,
      _8671: x0 => x0.done,
      _8851: x0 => x0.size,
      _8852: x0 => x0.type,
      _8859: x0 => x0.name,
      _8865: x0 => x0.length,
      _8870: x0 => x0.result,
      _9367: x0 => x0.url,
      _9369: x0 => x0.status,
      _9371: x0 => x0.statusText,
      _9372: x0 => x0.headers,
      _9373: x0 => x0.body,
      _11779: (x0,x1) => { x0.display = x1 },
      _13001: x0 => x0.name,
      _13709: () => globalThis.console,
      _13737: x0 => x0.name,
      _13738: x0 => x0.message,
      _13739: x0 => x0.code,
      _13741: x0 => x0.customData,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
