// Compiles a dart2wasm-generated main module from `source` which can then
// instantiatable via the `instantiate` method.
//
// `source` needs to be a `Response` object (or promise thereof) e.g. created
// via the `fetch()` JS API.
export async function compileStreaming(source) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(
      await WebAssembly.compileStreaming(source, builtins), builtins);
}

// Compiles a dart2wasm-generated wasm modules from `bytes` which is then
// instantiatable via the `instantiate` method.
export async function compile(bytes) {
  const builtins = {builtins: ['js-string']};
  return new CompiledApp(await WebAssembly.compile(bytes, builtins), builtins);
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export async function instantiate(modulePromise, importObjectPromise) {
  var moduleOrCompiledApp = await modulePromise;
  if (!(moduleOrCompiledApp instanceof CompiledApp)) {
    moduleOrCompiledApp = new CompiledApp(moduleOrCompiledApp);
  }
  const instantiatedApp = await moduleOrCompiledApp.instantiate(await importObjectPromise);
  return instantiatedApp.instantiatedModule;
}

// DEPRECATED: Please use `compile` or `compileStreaming` to get a compiled app,
// use `instantiate` method to get an instantiated app and then call
// `invokeMain` to invoke the main function.
export const invoke = (moduleInstance, ...args) => {
  moduleInstance.exports.$invokeMain(args);
}

class CompiledApp {
  constructor(module, builtins) {
    this.module = module;
    this.builtins = builtins;
  }

  // The second argument is an options object containing:
  // `loadDeferredModule` is a JS function that takes a module name matching a
  //   wasm file produced by the dart2wasm compiler and returns the bytes to
  //   load the module. These bytes can be in either a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  // `loadDynamicModule` is a JS function that takes two string names matching,
  //   in order, a wasm file produced by the dart2wasm compiler during dynamic
  //   module compilation and a corresponding js file produced by the same
  //   compilation. It should return a JS Array containing 2 elements. The first
  //   should be the bytes for the wasm module in a format supported by
  //   `WebAssembly.compile` or `WebAssembly.compileStreaming`. The second
  //   should be the result of using the JS 'import' API on the js file path.
  // `loadDeferredId` is a JS function that takes a string corresponding to a load
  //   ID generated by the compiler when 'load-ids' option is passed. Each load
  //   ID maps to one or more WASM modules produced by the compiler. This
  //   function should return an array of byte arrays corresponding to all the
  //   modules specified by that load ID. The arrays should be in a format
  //   supported by `WebAssembly.compile` or `WebAssembly.compileStreaming`.
  async instantiate(additionalImports,
      {loadDeferredModule, loadDynamicModule, loadDeferredId} = {}) {
    let dartInstance;

    // Prints to the console
    function printToConsole(value) {
      if (typeof dartPrint == "function") {
        dartPrint(value);
        return;
      }
      if (typeof console == "object" && typeof console.log != "undefined") {
        console.log(value);
        return;
      }
      if (typeof print == "function") {
        print(value);
        return;
      }

      throw "Unable to print message: " + value;
    }

    // A special symbol attached to functions that wrap Dart functions.
    const jsWrappedDartFunctionSymbol = Symbol("JSWrappedDartFunction");

    function finalizeWrapper(dartFunction, wrapped) {
      wrapped.dartFunction = dartFunction;
      wrapped[jsWrappedDartFunctionSymbol] = true;
      return wrapped;
    }

    // Imports
    const dart2wasm = {
            _1: (decoder, codeUnits) => decoder.decode(codeUnits),
      _2: () => new TextDecoder("utf-8", {fatal: true}),
      _3: () => new TextDecoder("utf-8", {fatal: false}),
      _4: (s) => +s,
      _5: x0 => new Uint8Array(x0),
      _6: (x0,x1,x2) => x0.set(x1,x2),
      _7: (x0,x1) => x0.transferFromImageBitmap(x1),
      _8: x0 => x0.arrayBuffer(),
      _9: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._9(f,arguments.length,x0) }),
      _10: x0 => new window.FinalizationRegistry(x0),
      _11: (x0,x1,x2,x3) => x0.register(x1,x2,x3),
      _12: (x0,x1) => x0.unregister(x1),
      _13: (x0,x1,x2) => x0.slice(x1,x2),
      _14: (x0,x1) => x0.decode(x1),
      _15: (x0,x1) => x0.segment(x1),
      _16: () => new TextDecoder(),
      _18: x0 => x0.buffer,
      _19: x0 => x0.wasmMemory,
      _20: () => globalThis.window._flutter_skwasmInstance,
      _21: x0 => x0.rasterStartMilliseconds,
      _22: x0 => x0.rasterEndMilliseconds,
      _23: x0 => x0.imageBitmaps,
      _139: (x0,x1) => x0.appendChild(x1),
      _170: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _171: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _172: (x0,x1) => new OffscreenCanvas(x0,x1),
      _173: x0 => x0.remove(),
      _174: (x0,x1) => x0.append(x1),
      _176: x0 => x0.unlock(),
      _177: x0 => x0.getReader(),
      _178: (x0,x1) => x0.item(x1),
      _179: x0 => x0.next(),
      _180: x0 => x0.now(),
      _181: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._181(f,arguments.length,x0) }),
      _182: (x0,x1) => x0.addListener(x1),
      _183: (x0,x1) => x0.removeListener(x1),
      _184: (x0,x1) => x0.matchMedia(x1),
      _185: (x0,x1) => x0.revokeObjectURL(x1),
      _186: x0 => x0.close(),
      _187: (x0,x1,x2,x3,x4) => ({type: x0,data: x1,premultiplyAlpha: x2,colorSpaceConversion: x3,preferAnimation: x4}),
      _188: x0 => new window.ImageDecoder(x0),
      _189: (x0,x1) => ({frameIndex: x0,completeFramesOnly: x1}),
      _190: (x0,x1) => x0.decode(x1),
      _191: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._191(f,arguments.length,x0) }),
      _192: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _194: (x0,x1) => x0.getModifierState(x1),
      _195: x0 => x0.preventDefault(),
      _196: x0 => x0.stopPropagation(),
      _197: (x0,x1) => x0.removeProperty(x1),
      _198: (x0,x1) => x0.prepend(x1),
      _199: x0 => new Intl.Locale(x0),
      _200: (x0,x1) => x0.observe(x1),
      _201: x0 => x0.disconnect(),
      _202: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._202(f,arguments.length,x0) }),
      _203: (x0,x1) => x0.getAttribute(x1),
      _204: (x0,x1) => x0.contains(x1),
      _205: (x0,x1) => x0.querySelector(x1),
      _206: x0 => x0.blur(),
      _207: x0 => x0.hasFocus(),
      _208: (x0,x1) => x0.removeAttribute(x1),
      _209: (x0,x1,x2) => x0.insertBefore(x1,x2),
      _210: (x0,x1) => x0.hasAttribute(x1),
      _211: (x0,x1) => x0.getModifierState(x1),
      _212: (x0,x1) => x0.createTextNode(x1),
      _213: x0 => x0.getBoundingClientRect(),
      _214: (x0,x1) => x0.closest(x1),
      _215: () => new Array(),
      _651: x0 => new Uint8Array(x0),
      _655: () => globalThis.window.flutterConfiguration,
      _657: x0 => x0.assetBase,
      _662: x0 => x0.canvasKitMaximumSurfaces,
      _663: x0 => x0.debugShowSemanticsNodes,
      _664: x0 => x0.hostElement,
      _665: x0 => x0.multiViewEnabled,
      _666: x0 => x0.nonce,
      _668: x0 => x0.fontFallbackBaseUrl,
      _678: x0 => x0.console,
      _679: x0 => x0.devicePixelRatio,
      _680: x0 => x0.document,
      _681: x0 => x0.history,
      _682: x0 => x0.innerHeight,
      _683: x0 => x0.innerWidth,
      _684: x0 => x0.location,
      _685: x0 => x0.navigator,
      _686: x0 => x0.visualViewport,
      _687: x0 => x0.performance,
      _689: x0 => x0.URL,
      _691: (x0,x1) => x0.getComputedStyle(x1),
      _692: x0 => x0.screen,
      _693: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._693(f,arguments.length,x0) }),
      _694: (x0,x1) => x0.requestAnimationFrame(x1),
      _698: (x0,x1) => x0.warn(x1),
      _700: (x0,x1) => x0.debug(x1),
      _701: x0 => globalThis.parseFloat(x0),
      _702: () => globalThis.window,
      _703: () => globalThis.Intl,
      _704: () => globalThis.Symbol,
      _705: (x0,x1,x2,x3,x4) => globalThis.createImageBitmap(x0,x1,x2,x3,x4),
      _707: x0 => x0.clipboard,
      _708: x0 => x0.maxTouchPoints,
      _709: x0 => x0.vendor,
      _710: x0 => x0.language,
      _711: x0 => x0.platform,
      _712: x0 => x0.userAgent,
      _713: (x0,x1) => x0.vibrate(x1),
      _714: x0 => x0.languages,
      _715: x0 => x0.documentElement,
      _716: (x0,x1) => x0.querySelector(x1),
      _717: (x0,x1) => x0.querySelectorAll(x1),
      _719: (x0,x1) => x0.createElement(x1),
      _722: (x0,x1) => x0.createEvent(x1),
      _723: x0 => x0.activeElement,
      _726: x0 => x0.head,
      _727: x0 => x0.body,
      _728: (x0,x1) => { x0.title = x1 },
      _732: x0 => x0.visibilityState,
      _733: () => globalThis.document,
      _734: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._734(f,arguments.length,x0) }),
      _735: (x0,x1) => x0.dispatchEvent(x1),
      _743: x0 => x0.target,
      _745: x0 => x0.timeStamp,
      _746: x0 => x0.type,
      _748: (x0,x1,x2,x3) => x0.initEvent(x1,x2,x3),
      _755: x0 => x0.firstChild,
      _759: x0 => x0.parentElement,
      _761: (x0,x1) => { x0.textContent = x1 },
      _762: x0 => x0.parentNode,
      _763: x0 => x0.nextSibling,
      _764: (x0,x1) => x0.removeChild(x1),
      _765: x0 => x0.isConnected,
      _773: x0 => x0.clientHeight,
      _774: x0 => x0.clientWidth,
      _775: x0 => x0.offsetHeight,
      _776: x0 => x0.offsetWidth,
      _777: x0 => x0.id,
      _778: (x0,x1) => { x0.id = x1 },
      _781: (x0,x1) => { x0.spellcheck = x1 },
      _782: x0 => x0.tagName,
      _783: x0 => x0.style,
      _786: (x0,x1) => x0.querySelectorAll(x1),
      _787: (x0,x1,x2) => x0.setAttribute(x1,x2),
      _788: (x0,x1) => { x0.tabIndex = x1 },
      _789: x0 => x0.tabIndex,
      _790: (x0,x1) => x0.focus(x1),
      _791: x0 => x0.scrollTop,
      _792: (x0,x1) => { x0.scrollTop = x1 },
      _793: x0 => x0.scrollLeft,
      _794: (x0,x1) => { x0.scrollLeft = x1 },
      _795: x0 => x0.classList,
      _797: (x0,x1) => { x0.className = x1 },
      _799: (x0,x1) => x0.getElementsByClassName(x1),
      _800: x0 => x0.click(),
      _801: (x0,x1) => x0.attachShadow(x1),
      _804: x0 => x0.computedStyleMap(),
      _805: (x0,x1) => x0.get(x1),
      _811: (x0,x1) => x0.getPropertyValue(x1),
      _812: (x0,x1,x2,x3) => x0.setProperty(x1,x2,x3),
      _813: x0 => x0.offsetLeft,
      _814: x0 => x0.offsetTop,
      _815: x0 => x0.offsetParent,
      _817: (x0,x1) => { x0.name = x1 },
      _818: x0 => x0.content,
      _819: (x0,x1) => { x0.content = x1 },
      _823: (x0,x1) => { x0.src = x1 },
      _824: x0 => x0.naturalWidth,
      _825: x0 => x0.naturalHeight,
      _829: (x0,x1) => { x0.crossOrigin = x1 },
      _831: (x0,x1) => { x0.decoding = x1 },
      _832: x0 => x0.decode(),
      _837: (x0,x1) => { x0.nonce = x1 },
      _841: (x0,x1) => { x0.width = x1 },
      _844: (x0,x1) => { x0.height = x1 },
      _847: (x0,x1) => x0.getContext(x1),
      _914: x0 => x0.width,
      _915: x0 => x0.height,
      _917: (x0,x1) => x0.fetch(x1),
      _918: x0 => x0.status,
      _920: x0 => x0.body,
      _921: x0 => x0.arrayBuffer(),
      _924: x0 => x0.read(),
      _925: x0 => x0.value,
      _926: x0 => x0.done,
      _933: x0 => x0.name,
      _934: x0 => x0.x,
      _935: x0 => x0.y,
      _938: x0 => x0.top,
      _939: x0 => x0.right,
      _940: x0 => x0.bottom,
      _941: x0 => x0.left,
      _951: x0 => x0.height,
      _952: x0 => x0.width,
      _953: x0 => x0.scale,
      _954: (x0,x1) => { x0.value = x1 },
      _957: (x0,x1) => { x0.placeholder = x1 },
      _959: (x0,x1) => { x0.name = x1 },
      _960: x0 => x0.selectionDirection,
      _961: x0 => x0.selectionStart,
      _962: x0 => x0.selectionEnd,
      _965: x0 => x0.value,
      _967: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _968: x0 => x0.readText(),
      _969: (x0,x1) => x0.writeText(x1),
      _971: x0 => x0.altKey,
      _972: x0 => x0.code,
      _973: x0 => x0.ctrlKey,
      _974: x0 => x0.key,
      _975: x0 => x0.keyCode,
      _976: x0 => x0.location,
      _977: x0 => x0.metaKey,
      _978: x0 => x0.repeat,
      _979: x0 => x0.shiftKey,
      _980: x0 => x0.isComposing,
      _982: x0 => x0.state,
      _983: (x0,x1) => x0.go(x1),
      _985: (x0,x1,x2,x3) => x0.pushState(x1,x2,x3),
      _986: (x0,x1,x2,x3) => x0.replaceState(x1,x2,x3),
      _987: x0 => x0.pathname,
      _988: x0 => x0.search,
      _989: x0 => x0.hash,
      _993: x0 => x0.state,
      _996: (x0,x1) => x0.createObjectURL(x1),
      _998: x0 => new Blob(x0),
      _1008: x0 => x0.matches,
      _1009: x0 => x0.matches,
      _1013: x0 => x0.relatedTarget,
      _1015: x0 => x0.clientX,
      _1016: x0 => x0.clientY,
      _1017: x0 => x0.offsetX,
      _1018: x0 => x0.offsetY,
      _1021: x0 => x0.button,
      _1022: x0 => x0.buttons,
      _1023: x0 => x0.ctrlKey,
      _1027: x0 => x0.pointerId,
      _1028: x0 => x0.pointerType,
      _1029: x0 => x0.pressure,
      _1030: x0 => x0.tiltX,
      _1031: x0 => x0.tiltY,
      _1032: x0 => x0.getCoalescedEvents(),
      _1035: x0 => x0.deltaX,
      _1036: x0 => x0.deltaY,
      _1037: x0 => x0.wheelDeltaX,
      _1038: x0 => x0.wheelDeltaY,
      _1039: x0 => x0.deltaMode,
      _1046: x0 => x0.changedTouches,
      _1049: x0 => x0.clientX,
      _1050: x0 => x0.clientY,
      _1053: x0 => x0.data,
      _1056: (x0,x1) => { x0.disabled = x1 },
      _1058: (x0,x1) => { x0.type = x1 },
      _1059: (x0,x1) => { x0.max = x1 },
      _1060: (x0,x1) => { x0.min = x1 },
      _1061: (x0,x1) => { x0.value = x1 },
      _1062: x0 => x0.value,
      _1063: x0 => x0.disabled,
      _1064: (x0,x1) => { x0.disabled = x1 },
      _1066: (x0,x1) => { x0.placeholder = x1 },
      _1068: (x0,x1) => { x0.name = x1 },
      _1069: (x0,x1) => { x0.autocomplete = x1 },
      _1071: x0 => x0.selectionDirection,
      _1072: x0 => x0.selectionStart,
      _1074: x0 => x0.selectionEnd,
      _1077: (x0,x1,x2) => x0.setSelectionRange(x1,x2),
      _1078: (x0,x1) => x0.add(x1),
      _1081: (x0,x1) => { x0.noValidate = x1 },
      _1082: (x0,x1) => { x0.method = x1 },
      _1083: (x0,x1) => { x0.action = x1 },
      _1089: (x0,x1) => x0.getContext(x1),
      _1091: x0 => x0.convertToBlob(),
      _1108: x0 => x0.orientation,
      _1109: x0 => x0.width,
      _1110: x0 => x0.height,
      _1111: (x0,x1) => x0.lock(x1),
      _1130: x0 => new ResizeObserver(x0),
      _1133: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1133(f,arguments.length,x0,x1) }),
      _1141: x0 => x0.length,
      _1142: x0 => x0.iterator,
      _1143: x0 => x0.Segmenter,
      _1144: x0 => x0.v8BreakIterator,
      _1145: (x0,x1) => new Intl.Segmenter(x0,x1),
      _1148: x0 => x0.language,
      _1149: x0 => x0.script,
      _1150: x0 => x0.region,
      _1168: x0 => x0.done,
      _1169: x0 => x0.value,
      _1170: x0 => x0.index,
      _1174: (x0,x1) => new Intl.v8BreakIterator(x0,x1),
      _1175: (x0,x1) => x0.adoptText(x1),
      _1176: x0 => x0.first(),
      _1177: x0 => x0.next(),
      _1178: x0 => x0.current(),
      _1191: x0 => x0.hostElement,
      _1192: x0 => x0.viewConstraints,
      _1195: x0 => x0.maxHeight,
      _1196: x0 => x0.maxWidth,
      _1197: x0 => x0.minHeight,
      _1198: x0 => x0.minWidth,
      _1199: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1199(f,arguments.length,x0) }),
      _1200: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1200(f,arguments.length,x0) }),
      _1201: (x0,x1) => ({addView: x0,removeView: x1}),
      _1204: x0 => x0.loader,
      _1205: () => globalThis._flutter,
      _1206: (x0,x1) => x0.didCreateEngineInitializer(x1),
      _1207: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1207(f,arguments.length,x0) }),
      _1208: (module,f) => finalizeWrapper(f, function() { return module.exports._1208(f,arguments.length) }),
      _1209: (x0,x1) => ({initializeEngine: x0,autoStart: x1}),
      _1212: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1212(f,arguments.length,x0) }),
      _1213: x0 => ({runApp: x0}),
      _1215: (x0,x1,x2) => x0.call(x1,x2),
      _1216: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1216(f,arguments.length,x0,x1) }),
      _1217: x0 => new Promise(x0),
      _1218: x0 => x0.length,
      _1219: () => globalThis.window.ImageDecoder,
      _1220: x0 => x0.tracks,
      _1222: x0 => x0.completed,
      _1224: x0 => x0.image,
      _1230: x0 => x0.displayWidth,
      _1231: x0 => x0.displayHeight,
      _1232: x0 => x0.duration,
      _1235: x0 => x0.ready,
      _1236: x0 => x0.selectedTrack,
      _1237: x0 => x0.repetitionCount,
      _1238: x0 => x0.frameCount,
      _1286: (x0,x1) => x0.createElement(x1),
      _1292: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1293: () => globalThis.window.navigator.userAgent,
      _1295: (x0,x1,x2,x3) => x0.addEventListener(x1,x2,x3),
      _1296: (x0,x1,x2,x3) => x0.removeEventListener(x1,x2,x3),
      _1297: (x0,x1) => x0.createElement(x1),
      _1304: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1327: () => globalThis.firebase_firestore.documentId(),
      _1328: (x0,x1) => new firebase_firestore.GeoPoint(x0,x1),
      _1329: x0 => globalThis.firebase_firestore.vector(x0),
      _1330: x0 => globalThis.firebase_firestore.Bytes.fromUint8Array(x0),
      _1332: (x0,x1) => globalThis.firebase_firestore.collection(x0,x1),
      _1334: (x0,x1) => globalThis.firebase_firestore.doc(x0,x1),
      _1337: x0 => x0.call(),
      _1376: (x0,x1) => globalThis.firebase_firestore.setDoc(x0,x1),
      _1389: x0 => globalThis.firebase_firestore.doc(x0),
      _1405: () => globalThis.firebase_firestore.serverTimestamp(),
      _1413: (x0,x1) => globalThis.firebase_firestore.getFirestore(x0,x1),
      _1415: x0 => globalThis.firebase_firestore.Timestamp.fromMillis(x0),
      _1416: (module,f) => finalizeWrapper(f, function() { return module.exports._1416(f,arguments.length) }),
      _1440: x0 => x0.path,
      _1463: x0 => x0.path,
      _1543: x0 => x0.decode(),
      _1544: (x0,x1,x2,x3) => x0.open(x1,x2,x3),
      _1545: (x0,x1,x2) => x0.setRequestHeader(x1,x2),
      _1546: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1546(f,arguments.length,x0) }),
      _1547: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1547(f,arguments.length,x0) }),
      _1548: x0 => x0.send(),
      _1549: () => new XMLHttpRequest(),
      _1570: x0 => x0.toJSON(),
      _1571: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1571(f,arguments.length,x0) }),
      _1572: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1572(f,arguments.length,x0) }),
      _1573: (x0,x1,x2) => x0.onAuthStateChanged(x1,x2),
      _1574: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1574(f,arguments.length,x0) }),
      _1575: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1575(f,arguments.length,x0) }),
      _1576: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1576(f,arguments.length,x0) }),
      _1577: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1577(f,arguments.length,x0) }),
      _1578: (x0,x1,x2) => x0.onIdTokenChanged(x1,x2),
      _1590: x0 => globalThis.firebase_auth.signInAnonymously(x0),
      _1598: (x0,x1) => globalThis.firebase_auth.connectAuthEmulator(x0,x1),
      _1621: x0 => globalThis.firebase_auth.OAuthProvider.credentialFromResult(x0),
      _1636: x0 => globalThis.firebase_auth.getAdditionalUserInfo(x0),
      _1637: (x0,x1,x2) => ({errorMap: x0,persistence: x1,popupRedirectResolver: x2}),
      _1638: (x0,x1) => globalThis.firebase_auth.initializeAuth(x0,x1),
      _1644: x0 => globalThis.firebase_auth.OAuthProvider.credentialFromError(x0),
      _1659: () => globalThis.firebase_auth.debugErrorMap,
      _1662: () => globalThis.firebase_auth.browserSessionPersistence,
      _1664: () => globalThis.firebase_auth.browserLocalPersistence,
      _1666: () => globalThis.firebase_auth.indexedDBLocalPersistence,
      _1669: x0 => globalThis.firebase_auth.multiFactor(x0),
      _1670: (x0,x1) => globalThis.firebase_auth.getMultiFactorResolver(x0,x1),
      _1672: x0 => x0.currentUser,
      _1686: x0 => x0.displayName,
      _1687: x0 => x0.email,
      _1688: x0 => x0.phoneNumber,
      _1689: x0 => x0.photoURL,
      _1690: x0 => x0.providerId,
      _1691: x0 => x0.uid,
      _1692: x0 => x0.emailVerified,
      _1693: x0 => x0.isAnonymous,
      _1694: x0 => x0.providerData,
      _1695: x0 => x0.refreshToken,
      _1696: x0 => x0.tenantId,
      _1697: x0 => x0.metadata,
      _1699: x0 => x0.providerId,
      _1700: x0 => x0.signInMethod,
      _1701: x0 => x0.accessToken,
      _1702: x0 => x0.idToken,
      _1703: x0 => x0.secret,
      _1714: x0 => x0.creationTime,
      _1715: x0 => x0.lastSignInTime,
      _1720: x0 => x0.code,
      _1722: x0 => x0.message,
      _1734: x0 => x0.email,
      _1735: x0 => x0.phoneNumber,
      _1736: x0 => x0.tenantId,
      _1759: x0 => x0.user,
      _1762: x0 => x0.providerId,
      _1763: x0 => x0.profile,
      _1764: x0 => x0.username,
      _1765: x0 => x0.isNewUser,
      _1768: () => globalThis.firebase_auth.browserPopupRedirectResolver,
      _1773: x0 => x0.displayName,
      _1774: x0 => x0.enrollmentTime,
      _1775: x0 => x0.factorId,
      _1776: x0 => x0.uid,
      _1778: x0 => x0.hints,
      _1779: x0 => x0.session,
      _1781: x0 => x0.phoneNumber,
      _1793: (x0,x1) => x0.getItem(x1),
      _1799: (x0,x1) => x0.appendChild(x1),
      _1802: (x0,x1,x2,x3) => globalThis.firebase_analytics.logEvent(x0,x1,x2,x3),
      _1804: (x0,x1) => globalThis.firebase_analytics.setAnalyticsCollectionEnabled(x0,x1),
      _1807: (x0,x1) => globalThis.firebase_analytics.initializeAnalytics(x0,x1),
      _1810: (x0,x1,x2) => x0.setItem(x1,x2),
      _1811: (x0,x1) => x0.querySelector(x1),
      _1812: x0 => ({type: x0}),
      _1813: (x0,x1) => new Blob(x0,x1),
      _1814: x0 => globalThis.URL.createObjectURL(x0),
      _1815: (x0,x1) => x0.item(x1),
      _1816: () => new FileReader(),
      _1818: (x0,x1) => x0.readAsArrayBuffer(x1),
      _1819: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1819(f,arguments.length,x0) }),
      _1820: (x0,x1,x2) => x0.removeEventListener(x1,x2),
      _1821: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1821(f,arguments.length,x0) }),
      _1822: (x0,x1,x2) => x0.addEventListener(x1,x2),
      _1823: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1823(f,arguments.length,x0) }),
      _1824: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1824(f,arguments.length,x0) }),
      _1825: (x0,x1) => x0.removeChild(x1),
      _1826: x0 => x0.click(),
      _1827: x0 => new Blob(x0),
      _1828: x0 => globalThis.URL.revokeObjectURL(x0),
      _1831: (x0,x1,x2,x3,x4,x5,x6,x7) => ({apiKey: x0,authDomain: x1,databaseURL: x2,projectId: x3,storageBucket: x4,messagingSenderId: x5,measurementId: x6,appId: x7}),
      _1832: (x0,x1) => globalThis.firebase_core.initializeApp(x0,x1),
      _1833: x0 => globalThis.firebase_core.getApp(x0),
      _1834: () => globalThis.firebase_core.getApp(),
      _1835: (x0,x1,x2) => globalThis.firebase_core.registerVersion(x0,x1,x2),
      _1837: () => globalThis.firebase_core.SDK_VERSION,
      _1843: x0 => x0.apiKey,
      _1845: x0 => x0.authDomain,
      _1847: x0 => x0.databaseURL,
      _1849: x0 => x0.projectId,
      _1851: x0 => x0.storageBucket,
      _1853: x0 => x0.messagingSenderId,
      _1855: x0 => x0.measurementId,
      _1857: x0 => x0.appId,
      _1859: x0 => x0.name,
      _1860: x0 => x0.options,
      _1863: (x0,x1) => x0.debug(x1),
      _1864: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1864(f,arguments.length,x0) }),
      _1865: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._1865(f,arguments.length,x0,x1) }),
      _1866: (x0,x1) => ({createScript: x0,createScriptURL: x1}),
      _1867: (x0,x1,x2) => x0.createPolicy(x1,x2),
      _1868: (x0,x1) => x0.createScriptURL(x1),
      _1869: (x0,x1,x2) => x0.createScript(x1,x2),
      _1870: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._1870(f,arguments.length,x0) }),
      _1871: (x0,x1) => x0.key(x1),
      _1881: Date.now,
      _1883: s => new Date(s * 1000).getTimezoneOffset() * 60,
      _1884: s => {
        if (!/^\s*[+-]?(?:Infinity|NaN|(?:\.\d+|\d+(?:\.\d*)?)(?:[eE][+-]?\d+)?)\s*$/.test(s)) {
          return NaN;
        }
        return parseFloat(s);
      },
      _1885: () => new Error().stack,
      _1886: () => typeof dartUseDateNowForTicks !== "undefined",
      _1887: () => 1000 * performance.now(),
      _1888: () => Date.now(),
      _1889: () => {
        // On browsers return `globalThis.location.href`
        if (globalThis.location != null) {
          return globalThis.location.href;
        }
        return null;
      },
      _1890: () => {
        return typeof process != "undefined" &&
               Object.prototype.toString.call(process) == "[object process]" &&
               process.platform == "win32"
      },
      _1891: () => new WeakMap(),
      _1892: (map, o) => map.get(o),
      _1893: (map, o, v) => map.set(o, v),
      _1894: (exn) => exn.toString(),
      _1895: (exn) => exn.stack,
      _1896: (exn) => {
        let stackString = exn.toString();
        let frames = stackString.split('\n');
        let drop = 2;
        if (frames[0] === 'Error') {
            drop += 1;
        }
        return frames.slice(drop).join('\n');
      },
      _1897: x0 => new WeakRef(x0),
      _1898: x0 => x0.deref(),
      _1905: () => globalThis.WeakRef,
      _1908: s => JSON.stringify(s),
      _1909: s => printToConsole(s),
      _1910: (o, p, r) => o.replaceAll(p, () => r),
      _1911: (o, p, r) => o.replace(p, () => r),
      _1912: Function.prototype.call.bind(String.prototype.toLowerCase),
      _1913: s => s.toUpperCase(),
      _1914: s => s.trim(),
      _1915: s => s.trimLeft(),
      _1916: s => s.trimRight(),
      _1917: (string, times) => string.repeat(times),
      _1918: Function.prototype.call.bind(String.prototype.indexOf),
      _1919: (s, p, i) => s.lastIndexOf(p, i),
      _1920: (string, token) => string.split(token),
      _1921: Object.is,
      _1924: (o, t) => typeof o === t,
      _1925: (o, c) => o instanceof c,
      _1926: o => Object.keys(o),
      _1929: (o, a) => o + a,
      _1956: x0 => new Array(x0),
      _1958: x0 => x0.length,
      _1960: (x0,x1) => x0[x1],
      _1961: (x0,x1,x2) => { x0[x1] = x2 },
      _1964: (x0,x1,x2) => new DataView(x0,x1,x2),
      _1966: x0 => new Int8Array(x0),
      _1967: (x0,x1,x2) => new Uint8Array(x0,x1,x2),
      _1969: x0 => new Uint8ClampedArray(x0),
      _1971: x0 => new Int16Array(x0),
      _1973: x0 => new Uint16Array(x0),
      _1975: x0 => new Int32Array(x0),
      _1977: x0 => new Uint32Array(x0),
      _1979: x0 => new Float32Array(x0),
      _1981: x0 => new Float64Array(x0),
      _2005: x0 => x0.random(),
      _2008: () => globalThis.Math,
      _2021: (ms, c) =>
      setTimeout(() => dartInstance.exports.$invokeCallback(c),ms),
      _2022: (handle) => clearTimeout(handle),
      _2023: (ms, c) =>
      setInterval(() => dartInstance.exports.$invokeCallback(c), ms),
      _2024: (handle) => clearInterval(handle),
      _2025: (c) =>
      queueMicrotask(() => dartInstance.exports.$invokeCallback(c)),
      _2026: () => Date.now(),
      _2027: (s, m) => {
        try {
          return new RegExp(s, m);
        } catch (e) {
          return String(e);
        }
      },
      _2028: (x0,x1) => x0.exec(x1),
      _2029: (x0,x1) => x0.test(x1),
      _2030: x0 => x0.pop(),
      _2032: o => o === undefined,
      _2034: o => typeof o === 'function' && o[jsWrappedDartFunctionSymbol] === true,
      _2036: o => {
        const proto = Object.getPrototypeOf(o);
        return proto === Object.prototype || proto === null;
      },
      _2037: o => o instanceof RegExp,
      _2038: (l, r) => l === r,
      _2039: o => o,
      _2040: o => o,
      _2041: o => o,
      _2042: b => !!b,
      _2043: o => o.length,
      _2045: (o, i) => o[i],
      _2046: f => f.dartFunction,
      _2047: () => ({}),
      _2048: () => [],
      _2050: () => globalThis,
      _2051: (constructor, args) => {
        const factoryFunction = constructor.bind.apply(
            constructor, [null, ...args]);
        return new factoryFunction();
      },
      _2052: (o, p) => p in o,
      _2053: (o, p) => o[p],
      _2054: (o, p, v) => o[p] = v,
      _2055: (o, m, a) => o[m].apply(o, a),
      _2057: o => String(o),
      _2058: (p, s, f) => p.then(s, (e) => f(e, e === undefined)),
      _2059: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2059(f,arguments.length,x0) }),
      _2060: (module,f) => finalizeWrapper(f, function(x0,x1) { return module.exports._2060(f,arguments.length,x0,x1) }),
      _2061: o => {
        if (o === undefined) return 1;
        var type = typeof o;
        if (type === 'boolean') return 2;
        if (type === 'number') return 3;
        if (type === 'string') return 4;
        if (o instanceof Array) return 5;
        if (ArrayBuffer.isView(o)) {
          if (o instanceof Int8Array) return 6;
          if (o instanceof Uint8Array) return 7;
          if (o instanceof Uint8ClampedArray) return 8;
          if (o instanceof Int16Array) return 9;
          if (o instanceof Uint16Array) return 10;
          if (o instanceof Int32Array) return 11;
          if (o instanceof Uint32Array) return 12;
          if (o instanceof Float32Array) return 13;
          if (o instanceof Float64Array) return 14;
          if (o instanceof DataView) return 15;
        }
        if (o instanceof ArrayBuffer) return 16;
        // Feature check for `SharedArrayBuffer` before doing a type-check.
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
            return 17;
        }
        if (o instanceof Promise) return 18;
        return 19;
      },
      _2062: o => [o],
      _2063: (o0, o1) => [o0, o1],
      _2064: (o0, o1, o2) => [o0, o1, o2],
      _2065: (o0, o1, o2, o3) => [o0, o1, o2, o3],
      _2066: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI8ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2067: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI8ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2068: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI16ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2069: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI16ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2070: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmI32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2071: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmI32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2072: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF32ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2073: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF32ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2074: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const getValue = dartInstance.exports.$wasmF64ArrayGet;
        for (let i = 0; i < length; i++) {
          jsArray[jsArrayOffset + i] = getValue(wasmArray, wasmArrayOffset + i);
        }
      },
      _2075: (jsArray, jsArrayOffset, wasmArray, wasmArrayOffset, length) => {
        const setValue = dartInstance.exports.$wasmF64ArraySet;
        for (let i = 0; i < length; i++) {
          setValue(wasmArray, wasmArrayOffset + i, jsArray[jsArrayOffset + i]);
        }
      },
      _2076: x0 => new ArrayBuffer(x0),
      _2077: s => {
        if (/[[\]{}()*+?.\\^$|]/.test(s)) {
            s = s.replace(/[[\]{}()*+?.\\^$|]/g, '\\$&');
        }
        return s;
      },
      _2078: x0 => x0.input,
      _2079: x0 => x0.index,
      _2080: x0 => x0.groups,
      _2081: x0 => x0.flags,
      _2082: x0 => x0.multiline,
      _2083: x0 => x0.ignoreCase,
      _2084: x0 => x0.unicode,
      _2085: x0 => x0.dotAll,
      _2086: (x0,x1) => { x0.lastIndex = x1 },
      _2087: (o, p) => p in o,
      _2088: (o, p) => o[p],
      _2089: (o, p, v) => o[p] = v,
      _2090: (o, p) => delete o[p],
      _2098: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2098(f,arguments.length,x0) }),
      _2099: (module,f) => finalizeWrapper(f, function(x0) { return module.exports._2099(f,arguments.length,x0) }),
      _2104: (x0,x1) => new WebSocket(x0,x1),
      _2105: (x0,x1) => x0.send(x1),
      _2106: (x0,x1,x2) => x0.close(x1,x2),
      _2108: x0 => x0.close(),
      _2111: () => new AbortController(),
      _2112: x0 => x0.abort(),
      _2113: (x0,x1,x2,x3,x4,x5) => ({method: x0,headers: x1,body: x2,credentials: x3,redirect: x4,signal: x5}),
      _2114: (x0,x1) => globalThis.fetch(x0,x1),
      _2115: (x0,x1) => x0.get(x1),
      _2116: (module,f) => finalizeWrapper(f, function(x0,x1,x2) { return module.exports._2116(f,arguments.length,x0,x1,x2) }),
      _2117: (x0,x1) => x0.forEach(x1),
      _2118: x0 => x0.getReader(),
      _2119: x0 => x0.cancel(),
      _2120: x0 => x0.read(),
      _2121: x0 => x0.trustedTypes,
      _2122: (x0,x1) => { x0.text = x1 },
      _2123: o => o instanceof Array,
      _2124: (a, i) => a.push(i),
      _2127: (a, l) => a.length = l,
      _2128: a => a.pop(),
      _2129: (a, i) => a.splice(i, 1),
      _2131: (a, s, e) => a.slice(s, e),
      _2133: (a, b) => a == b ? 0 : (a > b ? 1 : -1),
      _2134: a => a.length,
      _2136: (a, i) => a[i],
      _2137: (a, i, v) => a[i] = v,
      _2139: o => {
        if (o instanceof ArrayBuffer) return 0;
        if (globalThis.SharedArrayBuffer !== undefined &&
            o instanceof SharedArrayBuffer) {
          return 1;
        }
        return 2;
      },
      _2140: (o, offsetInBytes, lengthInBytes) => {
        var dst = new ArrayBuffer(lengthInBytes);
        new Uint8Array(dst).set(new Uint8Array(o, offsetInBytes, lengthInBytes));
        return new DataView(dst);
      },
      _2142: o => o instanceof Uint8Array,
      _2143: (o, start, length) => new Uint8Array(o.buffer, o.byteOffset + start, length),
      _2144: o => o instanceof Int8Array,
      _2145: (o, start, length) => new Int8Array(o.buffer, o.byteOffset + start, length),
      _2146: o => o instanceof Uint8ClampedArray,
      _2147: (o, start, length) => new Uint8ClampedArray(o.buffer, o.byteOffset + start, length),
      _2148: o => o instanceof Uint16Array,
      _2149: (o, start, length) => new Uint16Array(o.buffer, o.byteOffset + start, length),
      _2150: o => o instanceof Int16Array,
      _2151: (o, start, length) => new Int16Array(o.buffer, o.byteOffset + start, length),
      _2152: o => o instanceof Uint32Array,
      _2153: (o, start, length) => new Uint32Array(o.buffer, o.byteOffset + start, length),
      _2154: o => o instanceof Int32Array,
      _2155: (o, start, length) => new Int32Array(o.buffer, o.byteOffset + start, length),
      _2157: (o, start, length) => new BigInt64Array(o.buffer, o.byteOffset + start, length),
      _2158: o => o instanceof Float32Array,
      _2159: (o, start, length) => new Float32Array(o.buffer, o.byteOffset + start, length),
      _2160: o => o instanceof Float64Array,
      _2161: (o, start, length) => new Float64Array(o.buffer, o.byteOffset + start, length),
      _2162: (t, s) => t.set(s),
      _2164: (o) => new DataView(o.buffer, o.byteOffset, o.byteLength),
      _2166: o => o.buffer,
      _2167: o => o.byteOffset,
      _2168: Function.prototype.call.bind(Object.getOwnPropertyDescriptor(DataView.prototype, 'byteLength').get),
      _2169: (b, o) => new DataView(b, o),
      _2170: (b, o, l) => new DataView(b, o, l),
      _2171: Function.prototype.call.bind(DataView.prototype.getUint8),
      _2172: Function.prototype.call.bind(DataView.prototype.setUint8),
      _2173: Function.prototype.call.bind(DataView.prototype.getInt8),
      _2174: Function.prototype.call.bind(DataView.prototype.setInt8),
      _2175: Function.prototype.call.bind(DataView.prototype.getUint16),
      _2176: Function.prototype.call.bind(DataView.prototype.setUint16),
      _2177: Function.prototype.call.bind(DataView.prototype.getInt16),
      _2178: Function.prototype.call.bind(DataView.prototype.setInt16),
      _2179: Function.prototype.call.bind(DataView.prototype.getUint32),
      _2180: Function.prototype.call.bind(DataView.prototype.setUint32),
      _2181: Function.prototype.call.bind(DataView.prototype.getInt32),
      _2182: Function.prototype.call.bind(DataView.prototype.setInt32),
      _2185: Function.prototype.call.bind(DataView.prototype.getBigInt64),
      _2186: Function.prototype.call.bind(DataView.prototype.setBigInt64),
      _2187: Function.prototype.call.bind(DataView.prototype.getFloat32),
      _2188: Function.prototype.call.bind(DataView.prototype.setFloat32),
      _2189: Function.prototype.call.bind(DataView.prototype.getFloat64),
      _2190: Function.prototype.call.bind(DataView.prototype.setFloat64),
      _2191: Function.prototype.call.bind(Number.prototype.toString),
      _2192: Function.prototype.call.bind(BigInt.prototype.toString),
      _2193: Function.prototype.call.bind(Number.prototype.toString),
      _2194: (d, digits) => d.toFixed(digits),
      _2207: () => globalThis.document,
      _2213: (x0,x1) => { x0.height = x1 },
      _2215: (x0,x1) => { x0.width = x1 },
      _2217: (x0,x1) => { x0.pointerEvents = x1 },
      _2226: x0 => x0.style,
      _2229: x0 => x0.src,
      _2230: (x0,x1) => { x0.src = x1 },
      _2231: x0 => x0.naturalWidth,
      _2232: x0 => x0.naturalHeight,
      _2248: x0 => x0.status,
      _2249: (x0,x1) => { x0.responseType = x1 },
      _2251: x0 => x0.response,
      _2361: (x0,x1) => { x0.draggable = x1 },
      _2377: x0 => x0.style,
      _2734: (x0,x1) => { x0.target = x1 },
      _2736: (x0,x1) => { x0.download = x1 },
      _2761: (x0,x1) => { x0.href = x1 },
      _3306: (x0,x1) => { x0.accept = x1 },
      _3320: x0 => x0.files,
      _3346: (x0,x1) => { x0.multiple = x1 },
      _3364: (x0,x1) => { x0.type = x1 },
      _3616: (x0,x1) => { x0.type = x1 },
      _3624: (x0,x1) => { x0.crossOrigin = x1 },
      _3626: (x0,x1) => { x0.text = x1 },
      _4083: () => globalThis.window,
      _4123: x0 => x0.document,
      _4126: x0 => x0.location,
      _4145: x0 => x0.navigator,
      _4407: x0 => x0.trustedTypes,
      _4408: x0 => x0.sessionStorage,
      _4409: x0 => x0.localStorage,
      _4424: x0 => x0.hostname,
      _4534: x0 => x0.userAgent,
      _4585: x0 => x0.data,
      _4742: x0 => x0.length,
      _4959: x0 => x0.readyState,
      _4968: x0 => x0.protocol,
      _4972: (x0,x1) => { x0.binaryType = x1 },
      _4975: x0 => x0.code,
      _4976: x0 => x0.reason,
      _6684: x0 => x0.signal,
      _6739: x0 => x0.baseURI,
      _6745: x0 => x0.firstChild,
      _6756: () => globalThis.document,
      _6839: x0 => x0.head,
      _7170: (x0,x1) => { x0.id = x1 },
      _7197: x0 => x0.children,
      _8516: x0 => x0.value,
      _8518: x0 => x0.done,
      _8698: x0 => x0.size,
      _8699: x0 => x0.type,
      _8706: x0 => x0.name,
      _8712: x0 => x0.length,
      _8717: x0 => x0.result,
      _9214: x0 => x0.url,
      _9216: x0 => x0.status,
      _9218: x0 => x0.statusText,
      _9219: x0 => x0.headers,
      _9220: x0 => x0.body,
      _11626: (x0,x1) => { x0.display = x1 },
      _12848: x0 => x0.name,
      _13556: () => globalThis.console,
      _13584: x0 => x0.name,
      _13585: x0 => x0.message,
      _13586: x0 => x0.code,
      _13588: x0 => x0.customData,

    };

    const baseImports = {
      dart2wasm: dart2wasm,
      Math: Math,
      Date: Date,
      Object: Object,
      Array: Array,
      Reflect: Reflect,
      WebAssembly: {
        JSTag: WebAssembly.JSTag,
      },
      "": new Proxy({}, { get(_, prop) { return prop; } }),

    };

    const jsStringPolyfill = {
      "charCodeAt": (s, i) => s.charCodeAt(i),
      "compare": (s1, s2) => {
        if (s1 < s2) return -1;
        if (s1 > s2) return 1;
        return 0;
      },
      "concat": (s1, s2) => s1 + s2,
      "equals": (s1, s2) => s1 === s2,
      "fromCharCode": (i) => String.fromCharCode(i),
      "length": (s) => s.length,
      "substring": (s, a, b) => s.substring(a, b),
      "fromCharCodeArray": (a, start, end) => {
        if (end <= start) return '';

        const read = dartInstance.exports.$wasmI16ArrayGet;
        let result = '';
        let index = start;
        const chunkLength = Math.min(end - index, 500);
        let array = new Array(chunkLength);
        while (index < end) {
          const newChunkLength = Math.min(end - index, 500);
          for (let i = 0; i < newChunkLength; i++) {
            array[i] = read(a, index++);
          }
          if (newChunkLength < chunkLength) {
            array = array.slice(0, newChunkLength);
          }
          result += String.fromCharCode(...array);
        }
        return result;
      },
      "intoCharCodeArray": (s, a, start) => {
        if (s === '') return 0;

        const write = dartInstance.exports.$wasmI16ArraySet;
        for (var i = 0; i < s.length; ++i) {
          write(a, start++, s.charCodeAt(i));
        }
        return s.length;
      },
      "test": (s) => typeof s == "string",
    };


    

    dartInstance = await WebAssembly.instantiate(this.module, {
      ...baseImports,
      ...additionalImports,
      
      "wasm:js-string": jsStringPolyfill,
    });
    dartInstance.exports.$setThisModule(dartInstance);

    return new InstantiatedApp(this, dartInstance);
  }
}

class InstantiatedApp {
  constructor(compiledApp, instantiatedModule) {
    this.compiledApp = compiledApp;
    this.instantiatedModule = instantiatedModule;
  }

  // Call the main function with the given arguments.
  invokeMain(...args) {
    this.instantiatedModule.exports.$invokeMain(args);
  }
}
